= dark-theme-everything
:toc:

This repo should hold how to make dark theme on all tools and services

== Contribution Guidelines
Please check that inside the topic, all of the titles are sorted to avoid 

== Applications
=== Gmail Mobile
Creating a dark-themed experience on mobile gmail client is explained here https://support.google.com/mail/answer/9460619

=== Slack
Making slack dark-themed is explained here https://slack.com/intl/en-il/help/articles/360019434914-Use-dark-mode-in-Slack

=== rstudio
Go to the dark corners of R language using this https://blog.rstudio.com/2017/08/30/rstudio-dark-theme/

=== Telegram
Communicate in the shadows of telegram using https://telegram.org/blog/android-streaming

== Websites
=== Google Search
A shiny star in a dark search browser can be toggled in https://www.google.com/preferences

=== GitHub
A beta release for it has come to be, see it here https://github.com/settings/appearance

=== Gmail
Manifesting you dark-mode (that's how it's called there) desires in gmail is explained here https://support.google.com/mail/answer/112508?hl=en&ref_topic=7280210

=== Google Chat
for making your conversations more secure, put a dark theme on it! https://workspaceupdates.googleblog.com/2021/08/dark-mode-for-google-chat-on-web.html

=== StackOverflow
Incarnating your grayscale version of StackOverflow, read this https://meta.stackoverflow.com/questions/395949/dark-mode-beta-help-us-root-out-low-contrast-and-un-converted-bits

=== SourceGraph
To invoke the inner shdowiness of SourceGraph, see this https://about.sourcegraph.com/blog/introducing-sourcegraph-server-2-3/

=== GitLab
A beta release has emerged from the light into the darkness, see https://docs.gitlab.com/ee/user/profile/preferences.html

=== LinkedIn
Exposing your inner darkness for this website, see https://www.linkedin.com/help/linkedin/answer/a524473/switch-between-dark-and-light-mode
