name: Verify URL's

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup golang
      uses: actions/setup-go@v3
      with:
        check-latest: true
    - name: Install vl
      run: |
        go install github.com/npxbr/verify-links/cmd/vl@latest
        # add to path. (setup-go doesn't do that)
        echo ${HOME}/go/bin >> $GITHUB_PATH
    - name: Install find
      run: sudo apt-get install find
    # TODO: add caching for this install 
    - name: Check URLs
      env:
       PATH: ${PATH}:/home/runner/go/bin
      run: |
       files_to_check=$( find . -name \*adoc)
       for file in ${files_to_check}; do
        vl "${file}"
       done
